config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

	belongs_to :user
	has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

	validates :comment, presence: true
	belongs_to :user
	belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :book
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!,except: [:top, :about]

	before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

	private

		def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
		end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    def create
	    book = Book.find(params[:book_id])
        comment = current_user.book_comments.new(book_comment_params)
        comment.book_id = book.id
        comment.save
        redirect_to request.referer
    end

    def destroy
        BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
        redirect_to request.referer
    end

    private

    def book_comment_params
        params.require(:book_comment).permit(:comment)
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created user successfully.'
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render :edit
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updateed user successfully.'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

def create
    book = Book.find(params[:book_id])
	favorite = current_user.favorites.new(book_id: book.id)
	favorite.save
    redirect_to request.referer
end

def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end

	def about
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def index
    @users = User.all
    @book = Book.new
	end

	def show
		@user = User.find(params[:id])
		@book = Book.new
		@books = @user.books
	end

	def edit
		@user = User.find(params[:id])
		if @user == current_user
    	render "edit"
     else
      redirect_to user_path(current_user.id)
     end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
		else
			render :edit
		end
	end

	private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
			<div id="error_explanation">
			<% if @book.errors.any? %>
    	<h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
    	<ul>
    		<% if @book.errors.include?(:title) %>
       		<li>
        		<%= @book.errors.full_messages_for(:title).first %>
      		<% end %>
       		</li>
     		<% if @book.errors.include?(:body) %>
    		<li>
       			<%= @book.errors.full_messages_for(:body).first %>
      		<% end %>
        	</li>
    	</ul>
    	<% end %>
  	</div>
			<h1>Editing Book</h1>
			<%= form_with model: @book, local:true do |f| %>
			<div class="form-group">
				<label for="bookTitle">Title</label></br>
			 	<%= f.text_field :title, autofocus: true, class:"form-control book-title", id:"book-title" %>
			</div>
  		<div class="form-group">
  			<label for="bookOpinion">Opinion</label></br>
  			<%= f.text_area :body, class:"form-control bookBody", id:"bookBody" %>
  		</div>
  		<div class="form-group">
            <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
			</div>
			<% end %>
			<%= link_to 'Show', book_path(@book.id), class: "@user.id" %>
			|
			<%= link_to 'Back', books_path, class: "back" %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
	<div id="error_explanation">
		<% if @book.errors.any? %>
    	<h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
    	<ul>
    		<% if @book.errors.include?(:title) %>
       		<li>
        		<%= @book.errors.full_messages_for(:title).first %>
      		<% end %>
       		</li>
     		<% if @book.errors.include?(:body) %>
    		<li>
       			<%= @book.errors.full_messages_for(:body).first %>
      		<% end %>
        	</li>
    	</ul>
    	<% end %>
  	</div>
	<div class="row">
		<div class="col-md-3">
			<h2>User info</h2>
			<%= attachment_image_tag current_user, :profile_image, size: "100x100", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %>
			<table class="table">
				<tbody>
					<tr></tr>
					<tr>
						<th>name</th>
						<th><%= current_user.name %></th>
					</tr>
					<tr>
						<th>introduction</th>
						<th><%= current_user.introduction %></th>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<%= link_to edit_user_path(current_user.id), class:"btn btn-outline-secondary btn-block" do %>
				<i class="fas fa-user-cog"></i>
				<% end %>
			</div>
			<h2 class="mt-3">New book</h2>
			<%= form_with model: @book, url:'/books', local:true do |f| %>
  			<div class="form-group">
  				<label for="book_title">Title</label>
  				<%= f.text_field :title, class:"form-control book_title", id:"book_title"%>
  			</div>
  			<div class="form-group">
  				<label for="book_opinion">Opinion</label>
  				<%= f.text_area :body, class:"form-control book_body", id:"book_body"%>
  			</div>
  			<div class="form-group">
  				<input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  			</div>
			<% end %>
		</div>

		<div class="col-md-8 offset-md-1">
			<h2>Books</h2>
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user.id) do %>
							<%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td>
						<%= link_to book.title, book_path(book.id) %>
						</td>
						<td>
						<%= book.body %>
						</td>
						 <td>
            			<% if book.favorited_by?(current_user) %>
            			<span>
              				<%= link_to book_favorites_path(book), class:"text-red", method: :delete do %>
                			<i class="fa fa-heart unlike" aria-hidden="true"></i> <%= book.favorites.count %>
              				<% end %>
            			</span>
            			<% else %>
            			<span>
              				<%= link_to book_favorites_path(book), class:"text-blue", method: :post do %>
               				<i class="fa fa-heart" aria-hidden="true"></i> <%= book.favorites.count %>
              				<% end %>
           		 		</span>
         	 			<% end %>
           				</td>
    			        <td>
    			    		<p>コメント数：<%= book.book_comments.count %></p>
    			        </td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div id="error_explanation">
		<% if @book.errors.any? %>
    	<h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
    	<ul>
    		<% if @book.errors.include?(:title) %>
       		<li>
        		<%= @book.errors.full_messages_for(:title).first %>
      		<% end %>
       		</li>
     		<% if @book.errors.include?(:body) %>
    		<li>
       			<%= @book.errors.full_messages_for(:body).first %>
      		<% end %>
        	</li>
    	</ul>
    	<% end %>
  	</div>
	<div class="row">
		<div class="col-md-3">
			<h2>User info</h2>
			<%= attachment_image_tag @book.user, :profile_image, size: "100x100", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %>
			<table class="table">
				<tbody>
					<tr></tr>
					<tr>
						<th>name</th>
						<th><%= @book.user.name %></th>
					</tr>
					<tr>
						<th>introduction</th>
						<th><%= @book.user.introduction %></th>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<% if @user.id == current_user.id %>
				<%= link_to edit_user_path(current_user.id), class:"btn btn-outline-secondary btn-block" do %>
				<i class="fas fa-user-cog"></i>
				<% end %>
			<% else %>
				<%= link_to edit_user_path(@book.user.id), class:"btn btn-outline-secondary btn-block" do %>
				<i class="fas fa-user-cog"></i>
				<% end %>
			<% end %>
			</div>
			<h2 class="mt-3">New book</h2>
			<%= form_with model: Book.new, url:'/books', method:'post', local:true do |f| %>
  			<div class="form-group">
  				<label for="book_title">Title</label>
  				<%= f.text_field :title, class:"form-control book_title", id:"book_title"%>
  			</div>
  			<div class="form-group">
  				<label for="book_opinion">Opinion</label>
  				<%= f.text_area :body, class:"form-control book_body", id:"book_body"%>
  			</div>
  			<div class="form-group">
  				<input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  			</div>
			<% end %>
		</div>

		<div class="col-md-8 offset-md-1">
			<h2>Book detail</h2>
			<table class="table">
				<tbody>
					<tr>
						<td>
						<%= link_to user_path(@book.user.id)do %>
						<%= attachment_image_tag @book.user, :profile_image, size: "40x40", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %></br>
						<%= @book.user.name %>
						<% end %>
						</td>
						<td>
						<%= link_to @book.title, book_path(@book.id) %>
						</td>
						<td>
						<%= @book.body %>
						</td>
						<td>
						<% if @book.user == current_user %>
							<%= link_to 'Edit' , edit_book_path(@book.id), class:	"btn btn-sm btn-success" %>
						<% else %>
							<% if @book.favorited_by?(current_user) %>
            		<span>
              		<%= link_to book_favorites_path(@book), class:"text-red", method: :delete do %>
                	<i class="fa fa-heart unlike" aria-hidden="true"></i> <%= @book.favorites.count %>
              		<% end %>
            		</span>
            	<% else %>
            		<span>
              		<%= link_to book_favorites_path(@book), class:"text-blue", method: :post do %>
               		<i class="fa fa-heart" aria-hidden="true"></i> <%= @book.favorites.count %>
              		<% end %>
           		 	</span>
         	 		<% end %>
						<% end %>
						</td>
						<% if @book.user == current_user %>
						<td>
							<%= link_to 'Destroy' , book_path(@book.id), method: :delete, class:"btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？"  %>
						</td>
						<% end %>
						<td>
							<p>コメント件数：<%= @book.book_comments.count %></p>
						</td>
					</tr>
				</tbody>
			</table>
			<table>
				<tbody>
					<div class="comments">
						<% @book.book_comments.each do |book_comment| %>
						<tr>
							<td>
									<p><%= attachment_image_tag book_comment.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></p>
									<%= link_to user_path(@book.user.id)do %>
									<%= book_comment.user.name %>
									<% end %>
						  </td>
						  <td>
								<p><%= book_comment.comment %></p>
							</td>
							<td>
		       			<% if book_comment.user == current_user %>
		          	<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
		        		<% end %>
		        	</td>
						</tr>
						<% end %>
					</div>
				</tbody>
			</table>
			<div class="new-comment">
				<%= form_with(model:[@book, @book_comment], local: true) do |f| %>
			  <%= f.text_area :comment, size: "100x5" %>
			  <%= f.submit "送信" %>
				<% end %>
			</div>

		</div>
	</div>
</div>

app/views/homes/about.html.erb
<div class="container">
	<div class="row">
		<h1 class="px-3 mx-auto">
			Welcome to
			<i class="fas fa-book">

			</i>
			<strong>Bookers</strong>
			!
		</h1>
	</div>
</div>

app/views/homes/top.html.erb
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to
            <i class="fas fa-book"></i>
            <strong>Bookers</strong>
             !!
            </h1>
            <p>
                In
                <i class="fas fa-book"></i>
                <strong>Bookers</strong>
                ,
            </p>
            <p>you can share and exchange your opinions , inpressions , and emotions</p>
            <p> about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                    <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
                </div>
                <div class="row">
                    <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
               <%= link_to 'Home', user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
              </li>
              <li>
                <%= link_to 'Users', users_path, class: 'fas fa-users nav-link text-light' %>
              </li>
              <li>
                <%= link_to 'Books', books_path, class: 'fas fa-book-open nav-link text-light' %>
              </li>
              <li>
                <%= link_to 'logout', destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
              </li>
              <% else %>
              <li>
               <a class="fas fa-home nav-link text-light" href="/"><%= "Home" %></a>
              </li>
              <li>
                <%= link_to 'About', home_about_path, class: 'fas fa-link nav-link text-light' %>
              </li>
              <li>
                <%= link_to 'sign up', new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
              </li>
              <li>
                <%= link_to 'login', new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <p id="notice"><%= notice %></p>
    <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
			<div id="error_explanation">
	 		<% if @user.errors.any? %>
    	<h2><%= @user.errors.count %> error prohibited this obj from being saved:</h2>
    	<ul>
    		<% if @user.errors.include?(:name) %>
       		<li>
        		<%= @user.errors.full_messages_for(:name).first %>
      		<% end %>
       		</li>
     		<% if @user.errors.include?(:introduction) %>
    		<li>
       			<%= @user.errors.full_messages_for(:introduction).first %>
      		<% end %>
        	</li>
    	</ul>
    	<% end %>
  	</div>
			<h2>User info</h2>
			<%= form_with model: @user, local:true do |f| %>
			<div class="form-group">
				<label for="userName">Name</label></br>
			 	<%= f.text_field :name, autofocus: true, class:"formControl name", id:"userName" %>
			</div>

			<div class="form-group">
  			<label for="inputImage">Image</label></br>
  			<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class:"formControl-fila userImage", id:"user_profile_image" %>
  		</div>

  		<div class="form-group">
  			<label for="user_introduction">Introduction</label></br>
  			<%= f.text_area :introduction, class:"form-control introduction", id:"user_introduction" %>
  		</div>
  		<div class="form-group">
            <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
	<div id="error_explanation">
		<% if @book.errors.any? %>
    	<h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
    	<ul>
    		<% if @book.errors.include?(:title) %>
       		<li>
        		<%= @book.errors.full_messages_for(:title).first %>
      		<% end %>
       		</li>
     		<% if @book.errors.include?(:body) %>
    		<li>
       			<%= @book.errors.full_messages_for(:body).first %>
      		<% end %>
        	</li>
    	</ul>
    	<% end %>
  	</div>
	<div class="row">
		<div class="col-md-3">
			<h2>User info</h2>
			<%= attachment_image_tag current_user, :profile_image, size: "100x100", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %>
			<table class="table">
				<tbody>
					<tr></tr>
					<tr>
						<th>name</th>
						<th><%= current_user.name %></th>
					</tr>
					<tr>
						<th>introduction</th>
						<th><%= current_user.introduction %></th>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<%= link_to edit_user_path(current_user.id), class:"btn btn-outline-secondary btn-block" do %>
				<i class="fas fa-user-cog"></i>
				<% end %>
			</div>
			<h2 class="mt-3">New book</h2>
			<%= form_with model: @book, url:'/books', local:true do |f| %>
  			<div class="form-group">
  			<label for="book_title">Title</label>
  			<%= f.text_field :title, class:"form-control book_title", id:"book_title"%>
  			</div>
  			<div class="form-group">
  			<label for="book_opinion">Opinion</label>
  			<%= f.text_area :body, class:"form-control book_body", id:"book_body"%>
  			</div>
  			<div class="form-group">
  			<input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  			</div>
			<% end %>
		</div>
		<div class="col-md-8 offset-md-1">
			<h2>Users</h2>
			<table class="table">
	 			<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</th>
				</thead>
				<tbody>
	  			<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg"%></td>
						<td><%= user.name %></td>
						<td><%= link_to 'Show', user_path(user.id), class: "@user.id" %></td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
	<div id="error_explanation">
		<% if @book.errors.any? %>
    	<h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
    	<ul>
    		<% if @book.errors.include?(:title) %>
       		<li>
        		<%= @book.errors.full_messages_for(:title).first %>
      		<% end %>
       		</li>
     		<% if @book.errors.include?(:body) %>
    		<li>
       			<%= @book.errors.full_messages_for(:body).first %>
      		<% end %>
        	</li>
    	</ul>
    	<% end %>
  	</div>
	<div class="row">
		<div class="col-md-3">
			<h2>User info</h2>
			<%= attachment_image_tag @user, :profile_image, size: "100x100", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %>
			<table class="table">
				<tbody>
					<tr></tr>
					<tr>
						<th>name</th>
						<th><%= @user.name %></th>
					</tr>
					<tr>
						<th>introduction</th>
						<th><%= @user.introduction %></th>
					</tr>
				</tbody>
			</table>
			<div class="row">
			<% if @user.id == current_user.id %>
				<%= link_to edit_user_path(current_user.id), class:"btn btn-outline-secondary btn-block" do %>
				<i class="fas fa-user-cog"></i>
				<% end %>
			<% else %>
				<%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
				<i class="fas fa-user-cog"></i>
				<% end %>
			<% end %>

			</div>
			<h2 class="mt-3">New book</h2>
			<%= form_with model: @book, url:'/books', local:true do |f| %>
  			<div class="form-group">
  			<label for="book_title">Title</label>
  			<%= f.text_field :title, class:"form-control book_title", id:"book_title"%>
  			</div>
  			<div class="form-group">
  			<label for="book_opinion">Opinion</label>
  			<%= f.text_area :body, class:"form-control book_body", id:"book_body"%>
  			</div>
  			<div class="form-group">
  			<input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  			</div>
			<% end %>
		</div>

		<div class="col-md-8 offset-md-1">
			<h2>Books</h2>
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
						<%= link_to user_path(@user.id)do %>
						<%= attachment_image_tag @user, :profile_image, size: "40x40", format: 'jpeg', class:"attachment user profile_image fallback", fallback: "no_image.jpg" %>
						<% end %>
						</td>
						<td>
						<%= link_to book.title, book_path(book.id) %>
						</td>
						<td>
						<%= book.body %>
						</td>
						<td>
							<p>コメント件数：<%= book.book_comments.count %></p>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>